package com.example.squadlink.ui.theme

import androidx.compose.ui.graphics.Color

// Light scheme - military sand + olive
val OlivePrimary = Color(0xFF2F5D3A)
val OliveOnPrimary = Color(0xFFF5F7F0)
val OliveSecondary = Color(0xFF6B7A3A)
val OliveOnSecondary = Color(0xFFF1F4E8)
val KhakiTertiary = Color(0xFFC2A36B)
val KhakiOnTertiary = Color(0xFF2A1F0B)
val OlivePrimaryContainer = Color(0xFF3F6B4A)
val OliveOnPrimaryContainer = Color(0xFFEAF4E5)
val OliveSecondaryContainer = Color(0xFF7A8842)
val OliveOnSecondaryContainer = Color(0xFFF5F7E8)
val KhakiTertiaryContainer = Color(0xFFD9C395)
val KhakiOnTertiaryContainer = Color(0xFF2A1F0B)
val SandBackground = Color(0xFFF4F1E6)
val SandSurface = Color(0xFFEDE8D8)
val SandSurfaceVariant = Color(0xFFD7D2C3)
val SandOnBackground = Color(0xFF1B1B16)
val SandOnSurface = Color(0xFF1B1B16)
val SandOnSurfaceVariant = Color(0xFF3B3A30)
val SandOutline = Color(0xFF7A776C)

// Dark scheme - night ops green
val NightPrimary = Color(0xFF8FBF7A)
val NightOnPrimary = Color(0xFF102013)
val NightSecondary = Color(0xFFA6B27F)
val NightOnSecondary = Color(0xFF1A1F12)
val NightTertiary = Color(0xFFD2B48C)
val NightOnTertiary = Color(0xFF2A1F0B)
val NightPrimaryContainer = Color(0xFF2B3F2A)
val NightOnPrimaryContainer = Color(0xFFCFE7C2)
val NightSecondaryContainer = Color(0xFF3A4226)
val NightOnSecondaryContainer = Color(0xFFE0E7C9)
val NightTertiaryContainer = Color(0xFF4A3C28)
val NightOnTertiaryContainer = Color(0xFFF0D9B4)
val NightBackground = Color(0xFF0E1110)
val NightSurface = Color(0xFF141815)
val NightSurfaceVariant = Color(0xFF2B322C)
val NightOnBackground = Color(0xFFE6E2D6)
val NightOnSurface = Color(0xFFE6E2D6)
val NightOnSurfaceVariant = Color(0xFFC8C2B1)
val NightOutline = Color(0xFF5C635A)
